### ISSUE TITLE
按照你的方式mock了page但还是提示 Page is not defined

### ISSUE THREAD

**Issue by Chaunjie** [zhengguorong/maizuo_wechat#1]
![image](https://user-images.githubusercontent.com/12093709/49923990-0ee07f80-fef0-11e8-97de-822f2cc59fc9.png)

**Comment by zhengguorong** [comment]
你代码仓库在哪，我需要调试下

**Comment by Chaunjie** [comment]
@zhengguorong 我下午整理下放一个demo上去

**Comment by Chaunjie** [comment]
@zhengguorong 抱歉，是我自己的问题导致的
