### ISSUE TITLE
测试覆盖率

### ISSUE THREAD

**Issue by kvchen95** [zhengguorong/maizuo_wechat#3]
author您好，我的代码中 大量使用三目运算 if else 导致代码覆盖率低 能提供一下怎么处理这些运算的思路吗 如请求返回值200则请求成功 否则请求失败处理

**Comment by zhengguorong** [comment]
简易函数不要定义过于复杂，单元测试的目的不单单为了解决覆盖问题，最重要的就是通过单元测试，发现代码的维护性，不可测试的代码就是不可维护的。
如果你只是为了覆盖if else等，那你就要mock大量场景，去测试单个函数

**Comment by kvchen95** [comment]
好的，但是没看到您代码里面的mock场景的代码，第一次做单元测试不是很了解jest，如需要根据请求返回的code进行处理：若200则setData，若非200则弹框提示 请求失败
这种场景应该怎样mock

**Comment by zhengguorong** [comment]
建议过一遍jest API，如果要测试基于网络的应用，你需要做一个独立的网络mock层，不要让应用依赖网络。
